// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { Database } from './types';

function createMockSupabaseAdminClient() {
  const dbPath = join(process.cwd(), 'db.json');

  const loadStore = () => {
    try {
      const data = readFileSync(dbPath, 'utf8');
      return JSON.parse(data);
    } catch (err) {
      // If file doesn't exist, return default data
      return {
        system_settings: [
          { id: 1, target_temp: 4, kp: 2, ki: 0.1, kd: 0.5, manual_override: false, compressor_manual: false, fan_manual: false },
        ],
        sensor_readings: [
          { id: 1, zone_id: 'main', temperature: 5.1, humidity: 68, ammonia: 0.42, energy_w: 122, compressor_on: true, fan_on: true, created_at: new Date().toISOString() },
        ],
        food_items: [],
        alerts: [],
        control_logs: [],
        ai_recommendations: [],
      };
    }
  };

  const saveStore = (store: Record<string, any[]>) => {
    try {
      writeFileSync(dbPath, JSON.stringify(store, null, 2));
    } catch (err) {
      console.error('Failed to save db.json:', err);
    }
  };

  const now = () => new Date().toISOString();
  const deepClone = <T>(value: T) => JSON.parse(JSON.stringify(value)) as T;

  let store = loadStore();

  type QueryState = {
    table: string;
    filters: Array<{ key: string; value: any }>;
    selects?: string[] | null;
    order?: { column: string; ascending: boolean };
    limit?: number;
    updatePayload?: Record<string, any>;
    deleteMode?: boolean;
    single?: boolean;
    maybeSingle?: boolean;
  };

  const normalizeRow = (row: any) => deepClone(row);
  const applyFilters = (rows: any[], filters: QueryState['filters']) => {
    return rows.filter((row) => filters.every((filter) => row[filter.key] === filter.value));
  };
  const applyOrder = (rows: any[], order?: QueryState['order']) => {
    if (!order) return rows;
    return [...rows].sort((a, b) => {
      const aVal = a[order.column];
      const bVal = b[order.column];
      if (aVal === bVal) return 0;
      if (aVal == null) return 1;
      if (bVal == null) return -1;
      const cmp = aVal > bVal ? 1 : -1;
      return order.ascending ? cmp : -cmp;
    });
  };

  const buildResult = (rows: any[], state: QueryState) => {
    let selected = rows;
    if (state.selects && state.selects.length > 0) {
      selected = rows.map((row) => {
        const result: Record<string, any> = {};
        state.selects!.forEach((field) => {
          if (field in row) {
            result[field] = row[field];
          }
        });
        return result;
      });
    }

    if (state.order) {
      selected = applyOrder(selected, state.order);
    }
    if (typeof state.limit === 'number') {
      selected = selected.slice(0, state.limit);
    }

    if (state.single) {
      return { data: selected[0] ?? null, error: null };
    }
    if (state.maybeSingle) {
      return { data: selected[0] ?? null, error: null };
    }
    return { data: selected, error: null };
  };

  const createBuilder = (table: string) => {
    const state: QueryState = {
      table,
      filters: [],
      selects: null,
      deleteMode: false,
      single: false,
      maybeSingle: false,
    };

    const execute = async () => {
      const rows = store[table] ?? [];
      const filtered = applyFilters(rows, state.filters);
      if (state.deleteMode) {
        const deleted = rows.filter((row) => !filtered.includes(row));
        store[table] = deleted;
        saveStore(store);
        return { data: filtered.map(normalizeRow), error: null };
      }
      if (state.updatePayload) {
        const updatedRows = rows.map((row) => {
          if (filtered.includes(row)) {
            return { ...row, ...state.updatePayload, updated_at: now() };
          }
          return row;
        });
        store[table] = updatedRows;
        saveStore(store);
        return { data: updatedRows.filter((row) => filtered.includes(row)).map(normalizeRow), error: null };
      }
      return buildResult(filtered.map(normalizeRow), state);
    };

    const builder: any = {
      select(columns?: string) {
        if (!columns || columns.trim() === '*') {
          state.selects = null;
        } else {
          state.selects = columns.split(',').map((c) => c.trim());
        }
        return this;
      },
      insert(payload: any) {
        const rows = Array.isArray(payload) ? payload : [payload];
        const inserted = rows.map((row) => {
          const nextId = store[table].length + 1;
          return { id: row.id ?? nextId, ...row, created_at: row.created_at ?? now() };
        });
        store[table] = store[table].concat(inserted);
        saveStore(store);
        return Promise.resolve({ data: inserted.map(normalizeRow), error: null });
      },
      update(payload: Record<string, any>) {
        state.updatePayload = payload;
        return this;
      },
      delete() {
        state.deleteMode = true;
        return this;
      },
      eq(key: string, value: any) {
        state.filters.push({ key, value });
        return this;
      },
      order(column: string, opts: { ascending?: boolean }) {
        state.order = { column, ascending: opts?.ascending ?? true };
        return this;
      },
      limit(count: number) {
        state.limit = count;
        return this;
      },
      maybeSingle() {
        state.maybeSingle = true;
        return this;
      },
      single() {
        state.single = true;
        return this;
      },
      then(resolve: any, reject: any) {
        return execute().then(resolve, reject);
      },
      catch(reject: any) {
        return execute().catch(reject);
      },
    };

    return builder;
  };

  console.warn('[Supabase] Missing Supabase env vars. Using local in-memory mock Supabase client for development.');
  return {
    from: (table: string) => createBuilder(table),
  } as any;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    if (process.env.NODE_ENV === 'production') {
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    return createMockSupabaseAdminClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
